// Generated by scripts/generate-bus-contract.mjs.
// Do not edit by hand; run `npm run contract:generate`.
export const GENERATED_BUS_CONTRACT_HASH = "7c9922de17837ff6";

export interface RepoStatus {
  modified: string[];
  staged: string[];
  untracked: string[];
}

export interface BranchInfo {
  name: string | null;
  detached: boolean;
  unborn: boolean;
  ahead: number | null;
  behind: number | null;
}

export interface CommitInfo {
  id: string;
  summary: string;
  author: string;
  timestamp: number;
}

export type DiffLineKind = "Added" | "Removed" | "Context";

export interface DiffLine {
  kind: DiffLineKind;
  content: string;
  old_lineno: number | null;
  new_lineno: number | null;
}

export interface DiffHunk {
  old_start: number;
  new_start: number;
  lines: DiffLine[];
}

export interface FileDiff {
  path: string;
  old_path: string | null;
  is_binary: boolean;
  hunks: DiffHunk[];
}

export type AgentSessionStatus =
  | "starting"
  | "running"
  | "exited"
  | "error"
  | "completed"
  | "failed"
  | "reverted";

export interface AgentSessionError {
  category: string;
  message: string;
}

export type AgentSessionCheckpointType = "git_ref" | "fs_snapshot";

export interface AgentSessionCheckpoint {
  checkpoint_type: AgentSessionCheckpointType;
  git_hash?: string | null;
  snapshot_files: string[];
}

export type AgentSessionChangeKind = "created" | "modified" | "removed";

export interface AgentSessionChange {
  path: string;
  kind: AgentSessionChangeKind;
  timestamp_ms: number;
}

export interface AgentSessionChangeLog {
  session_id: string;
  changes: AgentSessionChange[];
}

export type AgentSessionTurnStatus = "waiting" | "working" | "settling";

export interface AgentSessionTurnCheckpoint {
  id: string;
  index: number;
  started_at_ms: number;
  ended_at_ms: number;
  checkpoint: AgentSessionCheckpoint;
  restore_checkpoint?: AgentSessionCheckpoint | null;
  changes: AgentSessionChange[];
}

export interface AgentSessionLimits {
  max_sessions: number;
  max_sessions_per_repo: number;
  max_lifetime_ms: number;
}

export interface AgentSessionRuntimeOptions {
  model?: string | null;
  reasoning_effort?: string | null;
  speed?: string | null;
}

export type AgentRuntimeCatalogStatus = "loading" | "ready" | "error";

export interface AgentRuntimeReasoningEffort {
  value: string;
  description: string;
}

export interface AgentRuntimeServiceTier {
  id: string;
  name: string;
  description: string;
}

export interface AgentRuntimeModel {
  id: string;
  model: string;
  display_name: string;
  description: string;
  supported_reasoning_efforts: AgentRuntimeReasoningEffort[];
  default_reasoning_effort: string;
  service_tiers?: AgentRuntimeServiceTier[];
  default_service_tier?: string | null;
  is_default: boolean;
}

export interface AgentRuntimeCatalog {
  status: AgentRuntimeCatalogStatus;
  source: string;
  models?: AgentRuntimeModel[];
  default_model?: string | null;
  error?: string | null;
  updated_at_ms: number;
}

export type AgentSessionGoalStatus =
  | "active"
  | "paused"
  | "blocked"
  | "usage_limited"
  | "budget_limited"
  | "complete";

export interface AgentSessionGoal {
  text: string;
  status: AgentSessionGoalStatus;
  token_budget?: number | null;
  tokens_used: number;
  time_used_seconds: number;
  created_at_ms: number;
  updated_at_ms: number;
}

export interface AgentSessionPersonality {
  name: string;
  updated_at_ms: number;
}

export interface AgentSessionPlanMode {
  enabled: boolean;
  updated_at_ms: number;
}

export interface AgentSessionFeedback {
  kind: string;
  text: string;
  created_at_ms: number;
}

export interface AgentSessionContextSummary {
  text: string;
  created_at_ms: number;
  source_events: number;
  source_turns: number;
}

export interface AgentSession {
  id: string;
  repo: string;
  agent_type: string;
  provider_session_id?: string | null;
  wsl_distro?: string | null;
  status: AgentSessionStatus;
  pid: number | null;
  started_at_ms: number;
  ended_at_ms?: number | null;
  exit_code: number | null;
  error: AgentSessionError | null;
  checkpoint?: AgentSessionCheckpoint | null;
  change_log?: AgentSessionChange[];
  turn_status: AgentSessionTurnStatus;
  turn_checkpoints?: AgentSessionTurnCheckpoint[];
  timeline?: AgentSessionTimelineItem[];
  runtime_options?: AgentSessionRuntimeOptions;
  goal?: AgentSessionGoal | null;
  personality?: AgentSessionPersonality | null;
  plan_mode?: AgentSessionPlanMode | null;
  feedback?: AgentSessionFeedback[];
  context_summary?: AgentSessionContextSummary | null;
  reverted_at_ms?: number | null;
  restored_to_turn_index?: number | null;
  active_sessions: number;
  age_ms: number;
  output_bytes_per_second?: number | null;
}

export interface AgentSessionOutput {
  session_id: string;
  chunk_base64: string;
  timestamp_ms: number;
}

export type AgentSessionTimelineKind =
  | "user_message"
  | "steer_message"
  | "agent_message"
  | "agent_progress"
  | "command_output"
  | "activity"
  | "lifecycle";

export interface AgentSessionAttachment {
  path: string;
  name: string;
  is_image: boolean;
}

export interface AgentSessionTimelineItem {
  session_id: string;
  id: string;
  kind: AgentSessionTimelineKind;
  text: string;
  timestamp_ms: number;
  attachments?: AgentSessionAttachment[];
}

export interface AgentJournalSessionSummary {
  id: string;
  repo: string;
  agent_type: string;
  wsl_distro?: string | null;
  status: AgentSessionStatus;
  started_at_ms: number;
  ended_at_ms?: number | null;
  updated_at_ms: number;
  event_count: number;
  first_user_message?: string | null;
  last_event_kind?: AgentSessionTimelineKind | null;
  last_event_text?: string | null;
  last_event_at_ms?: number | null;
}

export type AgentHostCommandStatus = "completed" | "unavailable";

export interface AgentReviewSummary {
  branch: string;
  changed_files: number;
  working_shortstat?: string | null;
  staged_shortstat?: string | null;
  files: string[];
  truncated_count: number;
}

export interface AgentReviewFinding {
  severity: string;
  title: string;
  detail: string;
  path?: string | null;
  line?: number | null;
}

export interface AgentHostCommandResult {
  command: string;
  status: AgentHostCommandStatus;
  message: string;
  session_id?: string | null;
  repo?: string | null;
  agent_type?: string | null;
  review_summary?: AgentReviewSummary | null;
  review_findings?: AgentReviewFinding[] | null;
}

export interface GitleaksSetupStatus {
  installed: boolean;
  version: string | null;
  binary_path: string | null;
}

export interface GitleaksInstallResult {
  installed: boolean;
  version: string | null;
  binary_path: string | null;
  method: string | null;
  message: string;
}

export interface RepoFetchPreview {
  remote: string;
  host: string;
  sanitized_url: string;
}

export interface RepoFetchResult {
  remote: string;
  host: string;
  fetched_at_ms: number;
}

export interface CommandError {
  category: string;
  message: string;
}

export type RepoErrorClass = "transient" | "terminal";

export interface RepoErrorState {
  class: RepoErrorClass;
  category: string;
  message: string;
}

export type SignalSeverity = "info" | "warning" | "critical";

export type PassiveSignalKind =
  | "sensitive_path"
  | "possible_secret"
  | "large_delete"
  | "config_change"
  | "test_change";

export interface PassiveSignal {
  kind: PassiveSignalKind;
  severity: SignalSeverity;
  path?: string | null;
  message: string;
}

export interface RepoMetrics {
  changed_files: number;
  lines_added: number;
  lines_removed: number;
}

export interface SecretFinding {
  path: string;
  line: number;
  rule_id: string;
  description: string;
}

export type SecretScanEngine = "gitleaks" | "heuristic";

export type SecretScanState = "not_run" | "clean" | "findings" | "degraded";

export interface SecretScanStatus {
  state: SecretScanState;
  engine?: SecretScanEngine | null;
  version?: string | null;
  failure_category?: string | null;
  message?: string | null;
  checked_at_ms?: number | null;
}

export interface RepoDelta {
  repo: string;
  revision: number;
  status: RepoStatus;
  branch: BranchInfo | null;
  head: CommitInfo | null;
  last_activity_ms: number;
  error: RepoErrorState | null;
  metrics: RepoMetrics;
  gitleaks_configured: boolean;
  agents_md_configured: boolean;
  signals?: PassiveSignal[];
  secret_findings?: SecretFinding[];
  secret_scan_status: SecretScanStatus;
  subscribed_diffs?: FileDiff[] | null;
}

export type FsEventKind = "created" | "modified" | "removed";

export interface FsEvent {
  path: string;
  kind: FsEventKind;
  timestamp_ms: number;
  size: number | null;
  size_delta: number | null;
  signals?: PassiveSignal[];
}

export interface FsEventBatch {
  repo: string;
  events: FsEvent[];
}

export interface WatchingState {
  available: boolean;
  reason?: string | null;
}

export interface SubscriptionTarget {
  repo: string;
  path?: string | null;
}

export interface TreeEntry {
  path: string;
  is_dir: boolean;
}

export interface RepoTree {
  entries: TreeEntry[];
  truncated: boolean;
}

export interface FileContent {
  encoding: ContentEncoding;
  content: string;
  truncated: boolean;
}

export type ContentEncoding = "utf8" | "base64";

export interface WorkbenchSnapshot {
  watching: WatchingState;
  repos: RepoDelta[];
}

export interface GeneratedBusContractTypeMap {
  RepoStatus: RepoStatus;
  BranchInfo: BranchInfo;
  CommitInfo: CommitInfo;
  DiffLineKind: DiffLineKind;
  DiffLine: DiffLine;
  DiffHunk: DiffHunk;
  FileDiff: FileDiff;
  AgentSessionStatus: AgentSessionStatus;
  AgentSessionError: AgentSessionError;
  AgentSessionCheckpointType: AgentSessionCheckpointType;
  AgentSessionCheckpoint: AgentSessionCheckpoint;
  AgentSessionChangeKind: AgentSessionChangeKind;
  AgentSessionChange: AgentSessionChange;
  AgentSessionChangeLog: AgentSessionChangeLog;
  AgentSessionTurnStatus: AgentSessionTurnStatus;
  AgentSessionTurnCheckpoint: AgentSessionTurnCheckpoint;
  AgentSessionLimits: AgentSessionLimits;
  AgentSessionRuntimeOptions: AgentSessionRuntimeOptions;
  AgentRuntimeCatalogStatus: AgentRuntimeCatalogStatus;
  AgentRuntimeReasoningEffort: AgentRuntimeReasoningEffort;
  AgentRuntimeServiceTier: AgentRuntimeServiceTier;
  AgentRuntimeModel: AgentRuntimeModel;
  AgentRuntimeCatalog: AgentRuntimeCatalog;
  AgentSessionGoalStatus: AgentSessionGoalStatus;
  AgentSessionGoal: AgentSessionGoal;
  AgentSessionPersonality: AgentSessionPersonality;
  AgentSessionPlanMode: AgentSessionPlanMode;
  AgentSessionFeedback: AgentSessionFeedback;
  AgentSessionContextSummary: AgentSessionContextSummary;
  AgentSession: AgentSession;
  AgentSessionOutput: AgentSessionOutput;
  AgentSessionTimelineKind: AgentSessionTimelineKind;
  AgentSessionAttachment: AgentSessionAttachment;
  AgentSessionTimelineItem: AgentSessionTimelineItem;
  AgentJournalSessionSummary: AgentJournalSessionSummary;
  AgentHostCommandStatus: AgentHostCommandStatus;
  AgentReviewSummary: AgentReviewSummary;
  AgentReviewFinding: AgentReviewFinding;
  AgentHostCommandResult: AgentHostCommandResult;
  GitleaksSetupStatus: GitleaksSetupStatus;
  GitleaksInstallResult: GitleaksInstallResult;
  RepoFetchPreview: RepoFetchPreview;
  RepoFetchResult: RepoFetchResult;
  CommandError: CommandError;
  RepoErrorClass: RepoErrorClass;
  RepoErrorState: RepoErrorState;
  SignalSeverity: SignalSeverity;
  PassiveSignalKind: PassiveSignalKind;
  PassiveSignal: PassiveSignal;
  RepoMetrics: RepoMetrics;
  SecretFinding: SecretFinding;
  SecretScanEngine: SecretScanEngine;
  SecretScanState: SecretScanState;
  SecretScanStatus: SecretScanStatus;
  RepoDelta: RepoDelta;
  FsEventKind: FsEventKind;
  FsEvent: FsEvent;
  FsEventBatch: FsEventBatch;
  WatchingState: WatchingState;
  SubscriptionTarget: SubscriptionTarget;
  TreeEntry: TreeEntry;
  RepoTree: RepoTree;
  FileContent: FileContent;
  ContentEncoding: ContentEncoding;
  WorkbenchSnapshot: WorkbenchSnapshot;
}
